name: Overtest continuous integration

on:
  release:
    types: [published, created, edited]
  push:
    branches:
      - master
      - develop
      - release/**
  pull_request:
    branches:
      - master
      - develop
      - feature/**

jobs:
  build_ubuntu:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@master
      
      - name: Setup .NET Core
        run: |
          Invoke-WebRequest -Uri "https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.ps1" -OutFile "dotnet-install.ps1"
          ./dotnet-install.ps1 -Architecture x64 --channel 3.1
        shell: pwsh
      - name: Setup Node.JS
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      
      - name: Install tools and dependencies (solution-wide)
        run: |
          dotnet tool restore
          dotnet restore
      - name: Dependencies and migrations for OWebApp project
        working-directory: ./owebapp
        run: |
          npm install
          npm run execute-webpack
          dotnet ef migrations remove
          dotnet ef migrations add initial
        
      - name: Build
        run: |
          dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore --verbosity normal
